CREATE TABLE tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  process_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (process_id) REFERENCES processes(id) ON DELETE CASCADE
);
